# Generated by Django 5.0.14 on 2026-08-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_token',
            field=models.CharField(default='CuOfH9aK9fY_aRQ4UbwEZTh04b3YI8pNzEsOEelTb44', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_token',
            field=models.CharField(default='FIuVfI7Qq7ops6eybbZJHcWzRMqF7XNZxOYRCOQQlnM', max_length=64, unique=True),
        ),
    ]
