# Generated by Django 5.0.14 on 2026-08-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_device_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_token',
            field=models.CharField(default='OBGfzwoypkcF3Dr5AcFF6WzmUMEjWO80XU5_vo1sjHA', max_length=64, unique=True),
        ),
    ]
