# Generated by Django 5.0.14 on 2026-08-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_message_whatsapp_id_alter_device_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_token',
            field=models.CharField(default='Ho7zABQXn8QWNOELFiZdkeySmxb4mS7XlY-P_wN5_XI', max_length=64, unique=True),
        ),
    ]
