# Generated by Django 5.0.14 on 2026-08-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_device_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_token',
            field=models.CharField(default='QZCE3d7yZ2-pDl2qS4GfA_FoHqZsx_myfI-37w9zens', max_length=64, unique=True),
        ),
    ]
