# Generated by Django 5.0.14 on 2026-08-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_device_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_token',
            field=models.CharField(default='O3S8QaMD0r24DLjHIrhO5a89OZBLcJbuKi--fLKC2mY', max_length=64, unique=True),
        ),
    ]
