# Generated by Django 5.0.14 on 2026-08-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_device_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_token',
            field=models.CharField(default='GSDm4VXDHh_zFPBMaUk2gFVKkp8U_-LdX16QwsfsGeE', max_length=64, unique=True),
        ),
    ]
