# Generated by Django 5.0.14 on 2026-08-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_device_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_token',
            field=models.CharField(default='Yn5Lr9eUHJXWoKKoaajaVrt4d4UvObpxJ6E7ZoiNu-U', max_length=64, unique=True),
        ),
    ]
