# Generated by Django 5.0.14 on 2026-08-11 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_device_device_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_token',
            field=models.CharField(default='BN8AgYFbQ7jU2cQ-9a8uZvxTxF7De6c8FdpWd6GLHY8', max_length=64, unique=True),
        ),
    ]
