# Generated by Django 5.0.14 on 2026-08-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_account_user_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_token',
            field=models.CharField(default='6RZfSDnYBa9N8QyhFuY3kDcXhJKLZMhNS32TzNNQMT4', max_length=64, unique=True),
        ),
    ]
