# Generated by Django 5.0.14 on 2026-08-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_device_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_token',
            field=models.CharField(default='DY3IhpMvy1Fs7Boo8FVTkNPwIF6kIbEVtIZ6EB1u_UM', max_length=64, unique=True),
        ),
    ]
