# Generated by Django 5.0.14 on 2026-08-17 13:12

from django.db import migrations, models


def dedupe_uids(apps, schema_editor):
    """Existing rows may share a blank uid inside a folder (the webhook path
    never set one), which the new (mail_account, folder, uid) unique constraint
    would reject. Give every blank/duplicate uid a stable synthetic value."""
    IncomingEmail = apps.get_model("mail", "IncomingEmail")
    seen = set()
    for row in IncomingEmail.objects.all().order_by("received_at").iterator():
        key = (row.mail_account_id, row.folder, row.uid)
        if not row.uid or key in seen:
            row.uid = f"legacy-{str(row.id)[:12]}"
            row.save(update_fields=["uid"])
            key = (row.mail_account_id, row.folder, row.uid)
        seen.add(key)


def backfill_thread_key(apps, schema_editor):
    from mail.models import thread_key_for

    IncomingEmail = apps.get_model("mail", "IncomingEmail")
    for row in IncomingEmail.objects.all().iterator():
        row.thread_key = thread_key_for(row.subject)
        row.save(update_fields=["thread_key"])


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(dedupe_uids, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='incomingemail',
            unique_together={('mail_account', 'folder', 'uid')},
        ),
        migrations.AddField(
            model_name='incomingemail',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='incomingemail',
            name='cc',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='incomingemail',
            name='in_reply_to',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incomingemail',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incomingemail',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incomingemail',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incomingemail',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incomingemail',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incomingemail',
            name='thread_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incomingemail',
            name='to_addrs',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='folder_map',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(backfill_thread_key, migrations.RunPython.noop),
    ]
