# Generated by Django 5.0.14 on 2026-08-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmessage',
            name='contact',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='incomingmessage',
            name='sender',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='message',
            name='target',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='incomingmessage',
            index=models.Index(fields=['device', '-received_at'], name='wa_incoming_dev_recv_idx'),
        ),
    ]
